name: gnosis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  gradients: ^0.1.1+2
  flutter:
    sdk: flutter
  go_router: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_nav_bar: ^5.0.6
  get:

flutter:
  uses-material-design: true

assets:
  - assets/images/
